ALTER TABLE STRIA_FLOW_NODES
 DROP PRIMARY KEY CASCADE;

DROP TABLE STRIA_FLOW_NODES CASCADE CONSTRAINTS;

CREATE TABLE STRIA_FLOW_NODES
(
  FLOWID         VARCHAR2(30 CHAR)              NOT NULL,
  ID             VARCHAR2(30 CHAR)              NOT NULL,
  NAME           VARCHAR2(50 CHAR)              NOT NULL,
  TYPE           VARCHAR2(20 CHAR)              NOT NULL,
  CANVAS_TOP     NUMBER(4),
  CANVAS_LEFT    NUMBER(4),
  DIV_WIDTH      NUMBER(4),
  DIV_HEIGHT     NUMBER(4),
  SOURCE_TYPE    VARCHAR2(50 CHAR),
  SERVICE_TYPE   VARCHAR2(20 CHAR),
  CLAZZ          VARCHAR2(300 CHAR),
  METHOD_NAME    VARCHAR2(30 CHAR),
  ARGS           VARCHAR2(300 CHAR),
  ARGS_CLAZZ     VARCHAR2(300 CHAR),
  VAR            VARCHAR2(20 CHAR),
  SUB_CONDITION  VARCHAR2(300 CHAR),
  REQUEST        VARCHAR2(20 CHAR),
  SERVICE_CODE   VARCHAR2(20 CHAR),
  MESSAGE_TYPE   VARCHAR2(4 CHAR),
  MESSAGE_CODE   VARCHAR2(4 CHAR),
  EVENT_ID       VARCHAR2(30 CHAR)
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE STRIA_FLOW_NODES IS 'Stria流程节点定义';

COMMENT ON COLUMN STRIA_FLOW_NODES.FLOWID IS '流程ID';

COMMENT ON COLUMN STRIA_FLOW_NODES.ID IS '节点ID';

COMMENT ON COLUMN STRIA_FLOW_NODES.NAME IS '节点描述';

COMMENT ON COLUMN STRIA_FLOW_NODES.TYPE IS '节点类型';

COMMENT ON COLUMN STRIA_FLOW_NODES.CANVAS_TOP IS '据上边界偏移量';

COMMENT ON COLUMN STRIA_FLOW_NODES.CANVAS_LEFT IS '据左边界偏移量';

COMMENT ON COLUMN STRIA_FLOW_NODES.DIV_WIDTH IS '节点图形宽度';

COMMENT ON COLUMN STRIA_FLOW_NODES.DIV_HEIGHT IS '节点图形高度';

COMMENT ON COLUMN STRIA_FLOW_NODES.SOURCE_TYPE IS '渠道';

COMMENT ON COLUMN STRIA_FLOW_NODES.SERVICE_TYPE IS '服务类型';

COMMENT ON COLUMN STRIA_FLOW_NODES.CLAZZ IS '服务执行class';

COMMENT ON COLUMN STRIA_FLOW_NODES.METHOD_NAME IS '服务执行方法';

COMMENT ON COLUMN STRIA_FLOW_NODES.ARGS IS '参数取值表达式';

COMMENT ON COLUMN STRIA_FLOW_NODES.ARGS_CLAZZ IS '参数class';

COMMENT ON COLUMN STRIA_FLOW_NODES.VAR IS '输出别名定义';

COMMENT ON COLUMN STRIA_FLOW_NODES.EVENT_ID IS '事件ID';


ALTER TABLE STRIA_FLOW_LINES
 DROP PRIMARY KEY CASCADE;

DROP TABLE STRIA_FLOW_LINES CASCADE CONSTRAINTS;

CREATE TABLE STRIA_FLOW_LINES
(
  FLOWID     VARCHAR2(30 CHAR)                  NOT NULL,
  ID         VARCHAR2(30 CHAR)                  NOT NULL,
  NAME       VARCHAR2(50 CHAR),
  TYPE       VARCHAR2(20 CHAR),
  FROM_NODE  VARCHAR2(20 CHAR),
  TO_NODE    VARCHAR2(20 CHAR),
  EXPR       VARCHAR2(300 CHAR)
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE STRIA_FLOW_LINES IS 'Stria流程连接线定义';

COMMENT ON COLUMN STRIA_FLOW_LINES.FLOWID IS '流程ID';

COMMENT ON COLUMN STRIA_FLOW_LINES.ID IS '连接线ID';

COMMENT ON COLUMN STRIA_FLOW_LINES.NAME IS '连接线描述';

COMMENT ON COLUMN STRIA_FLOW_LINES.TYPE IS '节点类型';

COMMENT ON COLUMN STRIA_FLOW_LINES.FROM_NODE IS '源节点';

COMMENT ON COLUMN STRIA_FLOW_LINES.TO_NODE IS '目标节点';

COMMENT ON COLUMN STRIA_FLOW_LINES.EXPR IS '布尔类型表达式，用于决策节点后的连接线';


ALTER TABLE STRIA_FLOW
 DROP PRIMARY KEY CASCADE;

DROP TABLE STRIA_FLOW CASCADE CONSTRAINTS;

CREATE TABLE STRIA_FLOW
(
  FLOWID      VARCHAR2(30 CHAR)                 NOT NULL,
  FLOW_TYPE   VARCHAR2(2 CHAR)                  DEFAULT '01'                  NOT NULL,
  TITLE       VARCHAR2(50 CHAR),
  INIT_NUM    NUMBER(4),
  VERSION     VARCHAR2(10 CHAR),
  STATE       NUMBER(1)                         DEFAULT 1,
  CREATETIME  VARCHAR2(20 CHAR),
  CREATOR     VARCHAR2(20 CHAR),
  DTP_FLAG    VARCHAR2(1 CHAR),
  TIME_OUT    NUMBER(4),
  PROD_TYPE   VARCHAR2(10 CHAR),
  EVENT_TYPE  VARCHAR2(20 CHAR)
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE STRIA_FLOW IS 'Stria流程定义';

COMMENT ON COLUMN STRIA_FLOW.FLOWID IS '流程ID';

COMMENT ON COLUMN STRIA_FLOW.FLOW_TYPE IS '流程类型 01-服务流程；02-事件流程';

COMMENT ON COLUMN STRIA_FLOW.TITLE IS '流程描述';

COMMENT ON COLUMN STRIA_FLOW.INIT_NUM IS '初始流程节数';

COMMENT ON COLUMN STRIA_FLOW.VERSION IS '版本号';

COMMENT ON COLUMN STRIA_FLOW.STATE IS '可用开关';

COMMENT ON COLUMN STRIA_FLOW.CREATETIME IS '创建时间';

COMMENT ON COLUMN STRIA_FLOW.CREATOR IS '创建人';

COMMENT ON COLUMN STRIA_FLOW.DTP_FLAG IS '全局事物管理开关';

COMMENT ON COLUMN STRIA_FLOW.TIME_OUT IS '流程处理超时时间';

COMMENT ON COLUMN STRIA_FLOW.PROD_TYPE IS '产品类型';

COMMENT ON COLUMN STRIA_FLOW.EVENT_TYPE IS '事件类型';


DROP TABLE FW_TRAN_INFO CASCADE CONSTRAINTS;

CREATE TABLE FW_TRAN_INFO
(
  SERVICE_ID          VARCHAR2(100 CHAR),
  KEY_VALUE           VARCHAR2(200 CHAR),
  TRAN_DATE           VARCHAR2(20 CHAR),
  TRAN_TIME           VARCHAR2(30 CHAR),
  IN_MSG              CLOB,
  OUT_MSG             CLOB,
  END_TIME            VARCHAR2(30 CHAR),
  BEAN_RESULT         BLOB,
  SOURCE_TYPE         VARCHAR2(2 CHAR),
  SEQ_NO              VARCHAR2(50 CHAR),
  PROGRAM_ID          VARCHAR2(10 CHAR),
  STATUS              VARCHAR2(1 CHAR),
  REFERENCE           VARCHAR2(50 CHAR),
  PLATFORM_ID         VARCHAR2(32 CHAR),
  REVERSAL_KEY_VALUE  VARCHAR2(200 CHAR)
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FW_REVERSAL_TRAN CASCADE CONSTRAINTS;

CREATE TABLE FW_REVERSAL_TRAN
(
  REVERSAL_ID       VARCHAR2(50 CHAR),
  REVERSAL_ARGS     BLOB,
  TRAN_DATE         VARCHAR2(20 CHAR),
  REVERSAL_DATE     VARCHAR2(20 CHAR),
  MAX_REVERSAL_CNT  INTEGER,
  REVERSAL_CNT      INTEGER,
  REVERSAL_BEAN_ID  VARCHAR2(20 CHAR),
  RET_CODE          VARCHAR2(20 CHAR),
  RET_MSG           VARCHAR2(100 CHAR),
  STATUS            VARCHAR2(1 CHAR)
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FM_RESOURCE_LOCK
 DROP PRIMARY KEY CASCADE;

DROP TABLE FM_RESOURCE_LOCK CASCADE CONSTRAINTS;

CREATE TABLE FM_RESOURCE_LOCK
(
  MODULE_ID    VARCHAR2(4 CHAR)                 NOT NULL,
  RESOURCE_ID  VARCHAR2(50 CHAR)                NOT NULL,
  STATUS       VARCHAR2(1 CHAR),
  TXID         VARCHAR2(20 CHAR)                NOT NULL
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN FM_RESOURCE_LOCK.MODULE_ID IS '模块';

COMMENT ON COLUMN FM_RESOURCE_LOCK.RESOURCE_ID IS '资源ID';

COMMENT ON COLUMN FM_RESOURCE_LOCK.STATUS IS '状态： L锁定';

COMMENT ON COLUMN FM_RESOURCE_LOCK.TXID IS '事务ID';


ALTER TABLE DEMO_CLACCT
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEMO_CLACCT CASCADE CONSTRAINTS;

CREATE TABLE DEMO_CLACCT
(
  UUID         VARCHAR2(32 CHAR)                NOT NULL,
  ACCT_NO      VARCHAR2(20 CHAR)                NOT NULL,
  ACCT_NAME    VARCHAR2(50 CHAR)                NOT NULL,
  CREATE_TIME  VARCHAR2(9 CHAR)                 NOT NULL,
  CREATE_DATE  VARCHAR2(8 CHAR)                 NOT NULL,
  BAL          NUMBER(17,2)                     NOT NULL,
  STATUS       VARCHAR2(1 CHAR)                 NOT NULL
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE DEMO_CLACCT IS '账户示例表';

COMMENT ON COLUMN DEMO_CLACCT.UUID IS '唯一编号';

COMMENT ON COLUMN DEMO_CLACCT.ACCT_NO IS '账号';

COMMENT ON COLUMN DEMO_CLACCT.ACCT_NAME IS '账号名称';

COMMENT ON COLUMN DEMO_CLACCT.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN DEMO_CLACCT.CREATE_DATE IS '创建日期';

COMMENT ON COLUMN DEMO_CLACCT.BAL IS '余额';

COMMENT ON COLUMN DEMO_CLACCT.STATUS IS '状态A-活动，C-销户';


DROP TABLE DEMO_ACCT CASCADE CONSTRAINTS;

CREATE TABLE DEMO_ACCT
(
  UUID         VARCHAR2(32 CHAR)                NOT NULL,
  ACCT_NO      VARCHAR2(20 CHAR)                NOT NULL,
  ACCT_NAME    VARCHAR2(50 CHAR)                NOT NULL,
  CREATE_TIME  VARCHAR2(9 CHAR)                 NOT NULL,
  CREATE_DATE  VARCHAR2(8 CHAR)                 NOT NULL,
  BAL          NUMBER(17,2)                     NOT NULL,
  STATUS       VARCHAR2(1 CHAR)                 NOT NULL
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE AC_SETTLEMENT_RULE
 DROP PRIMARY KEY CASCADE;

DROP TABLE AC_SETTLEMENT_RULE CASCADE CONSTRAINTS;

CREATE TABLE AC_SETTLEMENT_RULE
(
  BRANCH              VARCHAR2(6 CHAR)          NOT NULL,
  SETTLE_LEVEL        VARCHAR2(2 CHAR)          NOT NULL,
  SETTLE_BRANCH       VARCHAR2(16 CHAR)         NOT NULL,
  SETTLE_SUBJECT      VARCHAR2(16 CHAR)         NOT NULL,
  SETTLE_ACCT_SEQ     VARCHAR2(2 CHAR)          NOT NULL,
  SETTLE_SUBJECT_UP   VARCHAR2(16 CHAR)         NOT NULL,
  SETTLE_ACCT_SEQ_UP  VARCHAR2(2 CHAR)          NOT NULL
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE AC_SETTLEMENT_RULE IS '清算规则表';

COMMENT ON COLUMN AC_SETTLEMENT_RULE.BRANCH IS '机构';

COMMENT ON COLUMN AC_SETTLEMENT_RULE.SETTLE_LEVEL IS '清算层级';

COMMENT ON COLUMN AC_SETTLEMENT_RULE.SETTLE_BRANCH IS '清算机构';

COMMENT ON COLUMN AC_SETTLEMENT_RULE.SETTLE_SUBJECT IS '清算科目';

COMMENT ON COLUMN AC_SETTLEMENT_RULE.SETTLE_ACCT_SEQ IS '清算账户序号';

COMMENT ON COLUMN AC_SETTLEMENT_RULE.SETTLE_SUBJECT_UP IS '上级清算科目';

COMMENT ON COLUMN AC_SETTLEMENT_RULE.SETTLE_ACCT_SEQ_UP IS '上级清算账户序号';


DROP TABLE BATCH_PARAM_TABLE_DEF CASCADE CONSTRAINTS;

CREATE TABLE BATCH_PARAM_TABLE_DEF
(
  SEQ_NO             VARCHAR2(32 CHAR),
  TABLE_NAME         VARCHAR2(30 CHAR),
  TARGET_TABLE_NAME  VARCHAR2(30 CHAR),
  DATA_SOURCE        VARCHAR2(20 CHAR),
  SELECT_NAMESPACE   VARCHAR2(100 CHAR),
  SELECT_SQL_ID      VARCHAR2(50 CHAR),
  INSERT_NAMESPACE   VARCHAR2(100 CHAR),
  INSERT_SQL_ID      VARCHAR2(50 CHAR),
  WHERE_SQL          VARCHAR2(1000 CHAR),
  BATCH_SIZE         NUMBER
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FW_SEQUENCES
 DROP PRIMARY KEY CASCADE;

DROP TABLE FW_SEQUENCES CASCADE CONSTRAINTS;

CREATE TABLE FW_SEQUENCES
(
  SEQ_NAME           VARCHAR2(50 CHAR)          NOT NULL,
  SEQ_CURRENT_VALUE  NUMBER                     NOT NULL,
  SEQ_MAX_VALUE      NUMBER                     DEFAULT 9999999999            NOT NULL,
  SEQ_MIN_VALUE      NUMBER                     DEFAULT 1                     NOT NULL,
  SEQ_INCREMENT_BY   NUMBER                     DEFAULT 1                     NOT NULL,
  SEQ_CYCLE          VARCHAR2(1 CHAR)           DEFAULT 'Y'                   NOT NULL,
  SEQ_CACHE          NUMBER                     DEFAULT 200                   NOT NULL
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN FW_SEQUENCES.SEQ_NAME IS '序列名称';

COMMENT ON COLUMN FW_SEQUENCES.SEQ_CURRENT_VALUE IS '序列值';

COMMENT ON COLUMN FW_SEQUENCES.SEQ_MAX_VALUE IS '最大序列值';

COMMENT ON COLUMN FW_SEQUENCES.SEQ_MIN_VALUE IS '最小序列之';

COMMENT ON COLUMN FW_SEQUENCES.SEQ_INCREMENT_BY IS '序列步长';

COMMENT ON COLUMN FW_SEQUENCES.SEQ_CYCLE IS '是否周期序列';

COMMENT ON COLUMN FW_SEQUENCES.SEQ_CACHE IS '缓存系列数';


ALTER TABLE DEMO_SEQ
 DROP PRIMARY KEY CASCADE;

DROP TABLE DEMO_SEQ CASCADE CONSTRAINTS;

CREATE TABLE DEMO_SEQ
(
  SEQ  VARCHAR2(30 BYTE)                        NOT NULL
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    0
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
COMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BATCH_DEF CASCADE CONSTRAINTS;

CREATE TABLE BATCH_DEF
(
  BATCH_CLASS  VARCHAR2(4 CHAR)                 NOT NULL,
  EOD_SOD      VARCHAR2(3 CHAR),
  BATCH_DESC   VARCHAR2(100 CHAR)
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BATCH_JOB_DEPENDENCY CASCADE CONSTRAINTS;

CREATE TABLE BATCH_JOB_DEPENDENCY
(
  DESCENDENT       VARCHAR2(30 CHAR)            NOT NULL,
  PREDECESSOR      VARCHAR2(30 CHAR)            NOT NULL,
  DEPENDENCY_TYPE  VARCHAR2(1 CHAR)             DEFAULT 'S'                   NOT NULL,
  STATUS           VARCHAR2(1 CHAR)             DEFAULT 'Y'                   NOT NULL
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BATCH_JOB_LINE_TYPE CASCADE CONSTRAINTS;

CREATE TABLE BATCH_JOB_LINE_TYPE
(
  DESCENDENT   VARCHAR2(30 CHAR)                NOT NULL,
  PREDECESSOR  VARCHAR2(30 CHAR)                NOT NULL,
  LINE_TYPE    VARCHAR2(10 CHAR)                DEFAULT 'sl'                  NOT NULL,
  M_VALUE      NUMBER
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BATCH_JOB_POS CASCADE CONSTRAINTS;

CREATE TABLE BATCH_JOB_POS
(
  JOB_ID    VARCHAR2(30 CHAR)                   NOT NULL,
  TOP_POS   INTEGER                             NOT NULL,
  LEFT_POS  INTEGER                             NOT NULL,
  WIDTH     INTEGER                             NOT NULL,
  HEIGHT    INTEGER                             NOT NULL
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BATCH_JOB_SPLIT_PARAM CASCADE CONSTRAINTS;

CREATE TABLE BATCH_JOB_SPLIT_PARAM
(
  JOB_ID         VARCHAR2(30 CHAR)              NOT NULL,
  SPLIT_CLASS    VARCHAR2(1 CHAR)               DEFAULT 'T'                   NOT NULL,
  SPLIT_TYPE     VARCHAR2(1 CHAR)               DEFAULT 'M'                   NOT NULL,
  SPLIT_CNT      INTEGER,
  MAX_PER_SPLIT  INTEGER,
  NAMESPACE      VARCHAR2(100 CHAR),
  SQL_ID         VARCHAR2(50 CHAR),
  FILE_PATH      VARCHAR2(100 CHAR),
  FILE_NAME      VARCHAR2(100 CHAR),
  FILE_FORMAT    VARCHAR2(50 CHAR),
  FILE_ROW_NAME  VARCHAR2(50 CHAR)
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BATCH_RUN_JOB CASCADE CONSTRAINTS;

CREATE TABLE BATCH_RUN_JOB
(
  JOB_ID      VARCHAR2(30 CHAR),
  JOB_STATUS  VARCHAR2(1 CHAR),
  SPLIT_CNT   INTEGER,
  FINISH_CNT  INTEGER,
  START_TIME  VARCHAR2(30 CHAR),
  END_TIME    VARCHAR2(30 CHAR),
  PERCENT     VARCHAR2(30 CHAR)
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BATCH_RUN_TASK CASCADE CONSTRAINTS;

CREATE TABLE BATCH_RUN_TASK
(
  TASK_ID       VARCHAR2(50 CHAR)               NOT NULL,
  JOB_ID        VARCHAR2(30 CHAR)               NOT NULL,
  TASK_STATUS   VARCHAR2(1 CHAR)                DEFAULT 'N'                   NOT NULL,
  SEQ_NO        INTEGER,
  START_ROW     NUMBER,
  END_ROW       NUMBER,
  FILE_OFFSET   NUMBER,
  FILE_LIMIT    NUMBER,
  SCHEMA_ID     VARCHAR2(30 CHAR),
  NODE_IP       VARCHAR2(30 CHAR),
  ERROR_DESC    VARCHAR2(4000 CHAR),
  START_TIME    VARCHAR2(30 CHAR),
  END_TIME      VARCHAR2(30 CHAR),
  SPLIT_JOB_ID  VARCHAR2(30 CHAR),
  SYSTEM_ID     VARCHAR2(30 CHAR),
  APP_ID        VARCHAR2(50 CHAR),
  RUN_MSG       VARCHAR2(200 CHAR),
  TASK_IND      VARCHAR2(50 CHAR),
  START_KEY     VARCHAR2(100 BYTE),
  END_KEY       VARCHAR2(100 BYTE),
  ERROR_MSG     VARCHAR2(500 CHAR),
  TIME_ELAPSED  NUMBER
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BATCH_STATUS CASCADE CONSTRAINTS;

CREATE TABLE BATCH_STATUS
(
  RUN_DATE      VARCHAR2(8 CHAR),
  BATCH_CLASS   VARCHAR2(4 CHAR),
  BATCH_STATUS  VARCHAR2(3 CHAR),
  STOP_BATCH    VARCHAR2(1 CHAR),
  START_TIME    VARCHAR2(30 CHAR),
  END_TIME      VARCHAR2(30 CHAR),
  BATCH_IND     VARCHAR2(50 CHAR)
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BATCH_STD_JOB CASCADE CONSTRAINTS;

CREATE TABLE BATCH_STD_JOB
(
  JOB_ID            VARCHAR2(30 CHAR)           NOT NULL,
  JOB_NAME          VARCHAR2(100 CHAR)          NOT NULL,
  BATCH_CLASS       VARCHAR2(4 CHAR)            NOT NULL,
  JOB_TYPE          VARCHAR2(4 CHAR)            NOT NULL,
  JOB_DESC          VARCHAR2(100 CHAR),
  MODULE_ID         VARCHAR2(4 CHAR)            NOT NULL,
  SYSTEM_ID         VARCHAR2(30 CHAR)           NOT NULL,
  DAY_END           VARCHAR2(1 CHAR)            DEFAULT 'Y'                   NOT NULL,
  WEEK_END          VARCHAR2(1 CHAR)            DEFAULT 'N'                   NOT NULL,
  MTH_END           VARCHAR2(1 CHAR)            DEFAULT 'N'                   NOT NULL,
  YR_END            VARCHAR2(1 CHAR)            DEFAULT 'N'                   NOT NULL,
  IS_SKIP           VARCHAR2(1 CHAR)            DEFAULT 'N'                   NOT NULL,
  GX_CLASS_NAME     VARCHAR2(100 CHAR),
  GX_METHOD         VARCHAR2(30 CHAR),
  STATIC_PARAM      VARCHAR2(100 CHAR),
  BY_SCHEMA         VARCHAR2(1 CHAR)            DEFAULT 'N'                   NOT NULL,
  IS_SPLIT          VARCHAR2(1 CHAR)            DEFAULT 'N'                   NOT NULL,
  STATUS            VARCHAR2(1 CHAR)            DEFAULT 'Y'                   NOT NULL,
  SHARD_MANAGER_ID  VARCHAR2(30 CHAR),
  BATCH_SIZE        NUMBER
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BATCH_TABLE_DEF CASCADE CONSTRAINTS;

CREATE TABLE BATCH_TABLE_DEF
(
  BATCH_TABLE_ID     VARCHAR2(20 CHAR),
  TABLE_NAME         VARCHAR2(30 CHAR),
  TARGET_TABLE_NAME  VARCHAR2(30 CHAR),
  SELECT_NAMESPACE   VARCHAR2(100 CHAR),
  SELECT_SQL_ID      VARCHAR2(50 CHAR),
  INSERT_NAMESPACE   VARCHAR2(100 CHAR),
  INSERT_SQL_ID      VARCHAR2(50 CHAR),
  WHERE_SQL          VARCHAR2(1000 CHAR),
  BATCH_SIZE         NUMBER
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BATCH_STATUS_HIST CASCADE CONSTRAINTS;

CREATE TABLE BATCH_STATUS_HIST
(
  RUN_DATE      VARCHAR2(8 CHAR),
  BATCH_CLASS   VARCHAR2(4 CHAR),
  BATCH_STATUS  VARCHAR2(3 CHAR),
  STOP_BATCH    VARCHAR2(1 CHAR),
  START_TIME    VARCHAR2(30 CHAR),
  END_TIME      VARCHAR2(30 CHAR),
  BATCH_IND     VARCHAR2(50 CHAR)
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BATCH_RUN_TASK_HIST CASCADE CONSTRAINTS;

CREATE TABLE BATCH_RUN_TASK_HIST
(
  TASK_ID       VARCHAR2(50 CHAR)               NOT NULL,
  JOB_ID        VARCHAR2(30 CHAR)               NOT NULL,
  TASK_STATUS   VARCHAR2(1 CHAR)                DEFAULT 'N'                   NOT NULL,
  SEQ_NO        INTEGER,
  START_ROW     NUMBER,
  END_ROW       NUMBER,
  FILE_OFFSET   NUMBER,
  FILE_LIMIT    NUMBER,
  SCHEMA_ID     VARCHAR2(30 CHAR),
  NODE_IP       VARCHAR2(30 CHAR),
  ERROR_DESC    VARCHAR2(4000 CHAR),
  START_TIME    VARCHAR2(30 CHAR),
  END_TIME      VARCHAR2(30 CHAR),
  SPLIT_JOB_ID  VARCHAR2(30 CHAR),
  SYSTEM_ID     VARCHAR2(30 CHAR),
  APP_ID        VARCHAR2(50 CHAR),
  RUN_MSG       VARCHAR2(200 CHAR),
  TASK_IND      VARCHAR2(50 CHAR),
  START_KEY     VARCHAR2(100 BYTE),
  END_KEY       VARCHAR2(100 BYTE),
  ERROR_MSG     VARCHAR2(500 CHAR),
  TIME_ELAPSED  NUMBER,
  RUN_DATE      VARCHAR2(8 CHAR)
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BATCH_RUN_JOB_HIST CASCADE CONSTRAINTS;

CREATE TABLE BATCH_RUN_JOB_HIST
(
  JOB_ID      VARCHAR2(30 CHAR),
  JOB_STATUS  VARCHAR2(1 CHAR),
  SPLIT_CNT   INTEGER,
  FINISH_CNT  INTEGER,
  START_TIME  VARCHAR2(30 CHAR),
  END_TIME    VARCHAR2(30 CHAR),
  PERCENT     VARCHAR2(30 CHAR),
  RUN_DATE    VARCHAR2(8 CHAR)
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE MB_ACCT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MB_ACCT CASCADE CONSTRAINTS;

CREATE TABLE MB_ACCT
(
  INTERNAL_KEY  VARCHAR2(30 CHAR)               NOT NULL,
  BASE_ACCT_NO  VARCHAR2(50 CHAR)               DEFAULT NULL,
  PROD_TYPE     VARCHAR2(10 CHAR),
  CCY           VARCHAR2(3 CHAR),
  BAL           NUMBER
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE IRL_ACCT_INT
 DROP PRIMARY KEY CASCADE;

DROP TABLE IRL_ACCT_INT CASCADE CONSTRAINTS;

CREATE TABLE IRL_ACCT_INT
(
  INTERNAL_KEY  VARCHAR2(30 CHAR)               NOT NULL,
  CCY           VARCHAR2(3 CHAR),
  AMOUNT        NUMBER
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE MB_TRAN_HIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE MB_TRAN_HIST CASCADE CONSTRAINTS;

CREATE TABLE MB_TRAN_HIST
(
  SEQ_NO        NUMBER,
  INTERNAL_KEY  VARCHAR2(30 CHAR)               NOT NULL,
  CCY           VARCHAR2(3 CHAR),
  AMOUNT        NUMBER
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE DTP_BRANCH
 DROP PRIMARY KEY CASCADE;

DROP TABLE DTP_BRANCH CASCADE CONSTRAINTS;

CREATE TABLE DTP_BRANCH
(
  BXID           VARCHAR2(32 CHAR)              NOT NULL,
  PARENTBXID     VARCHAR2(32 CHAR),
  TXID           VARCHAR2(32 CHAR)              NOT NULL,
  INDEXINBRANCH  NUMBER(11)                     DEFAULT '-1'                  NOT NULL,
  INDEXINTRUNK   NUMBER(11)                     DEFAULT '-1'                  NOT NULL,
  STATUS         VARCHAR2(20 CHAR)              NOT NULL,
  APPGROUP       VARCHAR2(50 CHAR)              NOT NULL
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE DTP_PREPARELOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE DTP_PREPARELOG CASCADE CONSTRAINTS;

CREATE TABLE DTP_PREPARELOG
(
  LOGID     VARCHAR2(32 BYTE)                   NOT NULL,
  BXID      VARCHAR2(32 BYTE)                   NOT NULL,
  TXID      VARCHAR2(32 BYTE)                   NOT NULL,
  LOGINDEX  NUMBER(11)                          DEFAULT '-1'                  NOT NULL,
  CONTENT   BLOB                                NOT NULL,
  STATUS    VARCHAR2(10 BYTE)                   NOT NULL
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (CONTENT) STORE AS 
      ( TABLESPACE  GALAXY_USER 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          TABLESPACE GALAXY_USER
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE DTP_SUBMITLOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE DTP_SUBMITLOG CASCADE CONSTRAINTS;

CREATE TABLE DTP_SUBMITLOG
(
  LOGID     VARCHAR2(32 BYTE)                   NOT NULL,
  BXID      VARCHAR2(32 BYTE)                   NOT NULL,
  TXID      VARCHAR2(32 BYTE)                   NOT NULL,
  LOGINDEX  NUMBER(11)                          DEFAULT '-1'                  NOT NULL,
  CONTENT   BLOB                                NOT NULL,
  STATUS    VARCHAR2(10 BYTE)                   NOT NULL
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (CONTENT) STORE AS 
      ( TABLESPACE  GALAXY_USER 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          TABLESPACE GALAXY_USER
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE DTP_TRUNK
 DROP PRIMARY KEY CASCADE;

DROP TABLE DTP_TRUNK CASCADE CONSTRAINTS;

CREATE TABLE DTP_TRUNK
(
  TXID       VARCHAR2(32 BYTE)                  NOT NULL,
  NEEDORDER  VARCHAR2(8 BYTE)                   NOT NULL,
  STATUS     VARCHAR2(20 BYTE)                  NOT NULL,
  APPGROUP   VARCHAR2(50 BYTE)                  NOT NULL,
  STARTTIME  NUMBER(32)                         DEFAULT '0'                   NOT NULL
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE DTP_RESOURCE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DTP_RESOURCE CASCADE CONSTRAINTS;

CREATE TABLE DTP_RESOURCE
(
  TABLENAME    VARCHAR2(32 BYTE)                NOT NULL,
  COLUMNNAME   VARCHAR2(32 BYTE)                NOT NULL,
  COLUMNVALUE  VARCHAR2(32 BYTE)                NOT NULL,
  TXID         VARCHAR2(32 BYTE)                NOT NULL
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE STATEINFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE STATEINFO CASCADE CONSTRAINTS;

CREATE TABLE STATEINFO
(
  ID  VARCHAR2(50 BYTE)                         NOT NULL
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE TEST_SPLIT CASCADE CONSTRAINTS;

CREATE TABLE TEST_SPLIT
(
  INT_COL   NUMBER,
  CHAR_COL  VARCHAR2(32 CHAR)
)
TABLESPACE GALAXY_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX AK_FW_REVERSAL_TRAN_P_FW_REVER ON FW_REVERSAL_TRAN
(REVERSAL_ID)
LOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX AK_FW_TRAN_INFO_PK_FW_TRAN_ ON FW_TRAN_INFO
(KEY_VALUE)
LOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX BATCH_DEF_PK ON BATCH_DEF
(BATCH_CLASS)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX BATCH_JOB_DEPENDENCY_PK ON BATCH_JOB_DEPENDENCY
(DESCENDENT, PREDECESSOR)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX BATCH_JOB_LINE_TYPE_PK ON BATCH_JOB_LINE_TYPE
(DESCENDENT, PREDECESSOR)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX BATCH_JOB_POS_PK ON BATCH_JOB_POS
(JOB_ID)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX BATCH_JOB_SPLIT_PARAM_PK ON BATCH_JOB_SPLIT_PARAM
(JOB_ID)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX BATCH_PARAM_TABLE_DEF_PK ON BATCH_PARAM_TABLE_DEF
(SEQ_NO)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX BATCH_RUN_JOB_HIST_IDX ON BATCH_RUN_JOB_HIST
(RUN_DATE, JOB_ID)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX BATCH_RUN_JOB_PK ON BATCH_RUN_JOB
(JOB_ID)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX BATCH_RUN_TASK_HIST_IDX1 ON BATCH_RUN_TASK_HIST
(RUN_DATE, JOB_ID)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX BATCH_RUN_TASK_IDX1 ON BATCH_RUN_TASK
(JOB_ID)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX BATCH_RUN_TASK_IDX2 ON BATCH_RUN_TASK
(TASK_STATUS)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX BATCH_RUN_TASK_PK ON BATCH_RUN_TASK
(TASK_ID)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX BATCH_STATUS_HIST_IDX ON BATCH_STATUS_HIST
(RUN_DATE, BATCH_CLASS)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX BATCH_STATUS_PK ON BATCH_STATUS
(BATCH_CLASS)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX BATCH_STD_JOB_PK ON BATCH_STD_JOB
(JOB_ID)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX BATCH_TABLE_DEF_PK ON BATCH_TABLE_DEF
(BATCH_TABLE_ID)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CHAR_INDEX ON TEST_SPLIT
(CHAR_COL)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DEMO_SEQ_PK ON DEMO_SEQ
(SEQ)
LOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FW_SEQUENCES_PK ON FW_SEQUENCES
(SEQ_NAME)
LOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX INT_INDEX ON TEST_SPLIT
(INT_COL)
NOLOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IRL_ACCT_INT ON IRL_ACCT_INT
(INTERNAL_KEY)
LOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MB_ACCT_PK ON MB_ACCT
(INTERNAL_KEY)
LOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX MB_TRAN_HIST_IDX ON MB_TRAN_HIST
(INTERNAL_KEY)
LOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MB_TRAN_HIST_PK ON MB_TRAN_HIST
(SEQ_NO)
LOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_AC_SETTLEMENT_RULE ON AC_SETTLEMENT_RULE
(BRANCH)
LOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_DEMO_CLACCT ON DEMO_CLACCT
(UUID)
LOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_FM_RESOURCE_LOCK ON FM_RESOURCE_LOCK
(MODULE_ID, RESOURCE_ID)
LOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_STRIA_FLOW ON STRIA_FLOW
(FLOWID)
LOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_STRIA_FLOW_LINES ON STRIA_FLOW_LINES
(FLOWID, ID)
LOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_STRIA_FLOW_NODES ON STRIA_FLOW_NODES
(FLOWID, ID)
LOGGING
TABLESPACE GALAXY_USER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE STRIA_FLOW_NODES ADD (
  CONSTRAINT PK_STRIA_FLOW_NODES
 PRIMARY KEY
 (FLOWID, ID)
    USING INDEX 
    TABLESPACE GALAXY_USER
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE STRIA_FLOW_LINES ADD (
  CONSTRAINT PK_STRIA_FLOW_LINES
 PRIMARY KEY
 (FLOWID, ID)
    USING INDEX 
    TABLESPACE GALAXY_USER
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE STRIA_FLOW ADD (
  CONSTRAINT PK_STRIA_FLOW
 PRIMARY KEY
 (FLOWID)
    USING INDEX 
    TABLESPACE GALAXY_USER
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FW_TRAN_INFO ADD (
  CONSTRAINT AK_FW_TRAN_INFO_PK_FW_TRAN_
 UNIQUE (KEY_VALUE));

ALTER TABLE FW_REVERSAL_TRAN ADD (
  CONSTRAINT AK_FW_REVERSAL_TRAN_P_FW_REVER
 UNIQUE (REVERSAL_ID));

ALTER TABLE FM_RESOURCE_LOCK ADD (
  CONSTRAINT PK_FM_RESOURCE_LOCK
 PRIMARY KEY
 (MODULE_ID, RESOURCE_ID)
    USING INDEX 
    TABLESPACE GALAXY_USER
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE DEMO_CLACCT ADD (
  CONSTRAINT PK_DEMO_CLACCT
 PRIMARY KEY
 (UUID));

ALTER TABLE AC_SETTLEMENT_RULE ADD (
  CONSTRAINT PK_AC_SETTLEMENT_RULE
 PRIMARY KEY
 (BRANCH));

ALTER TABLE FW_SEQUENCES ADD (
  CONSTRAINT FW_SEQUENCES_PK
 PRIMARY KEY
 (SEQ_NAME)
    USING INDEX 
    TABLESPACE GALAXY_USER
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE DEMO_SEQ ADD (
  CONSTRAINT DEMO_SEQ_PK
 PRIMARY KEY
 (SEQ)
    USING INDEX 
    TABLESPACE GALAXY_USER
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE MB_ACCT ADD (
  CONSTRAINT MB_ACCT_PK
 PRIMARY KEY
 (INTERNAL_KEY));

ALTER TABLE IRL_ACCT_INT ADD (
  CONSTRAINT IRL_ACCT_INT
 PRIMARY KEY
 (INTERNAL_KEY));

ALTER TABLE MB_TRAN_HIST ADD (
  CONSTRAINT MB_TRAN_HIST_PK
 PRIMARY KEY
 (SEQ_NO));

ALTER TABLE DTP_BRANCH ADD (
  PRIMARY KEY
 (BXID)
    USING INDEX 
    TABLESPACE GALAXY_USER
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE DTP_PREPARELOG ADD (
  PRIMARY KEY
 (LOGID)
    USING INDEX 
    TABLESPACE GALAXY_USER
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE DTP_SUBMITLOG ADD (
  PRIMARY KEY
 (LOGID)
    USING INDEX 
    TABLESPACE GALAXY_USER
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE DTP_TRUNK ADD (
  PRIMARY KEY
 (TXID)
    USING INDEX 
    TABLESPACE GALAXY_USER
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE DTP_RESOURCE ADD (
  PRIMARY KEY
 (TABLENAME, COLUMNNAME, COLUMNVALUE)
    USING INDEX 
    TABLESPACE GALAXY_USER
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE STATEINFO ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE GALAXY_USER
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

